### PR TITLE
Add coverage reports to channelflow

### PR DESCRIPTION
**Pull request by alalazo**
This PR adds coverage computation to our CI workflow. Coverage is displayed:

- At the end of the second CI job on Travis.
- On [codecov](https://codecov.io) once the service is set-up properly

### CODE REVIEW

**Comment by sajjadazimi** [comment]
codecov is enabled

**Comment by alalazo** [comment]
@sajjadazimi Yes, thanks. It seems the reports are generated too. I'll configure what needs to be reported and ping you when done.

**Review by symtor — APPROVED** [review]
Looks okay for me

**Comment by alalazo** [comment]
@epfl-ecps/dev The report is correctly generated on codecov. I also added badges for:
- Travis build status
- Codecov coverage percentage
- License type

at the top of the README file. If you view this file from the PR you can get an idea how it does look like.

**Review by sajjadazimi — APPROVED** [review]

**Pull request merged**
