### PR TITLE
Remove using namespace directives from header files

### PR DESCRIPTION
**Pull request by alalazo**
Having these kind of directives might cause namespace pollution. It's considered good practice to avoid them in header files, as they are included elsewhere and might import names into scope (which in turn
might change overload resolution or other mechanisms in unexpected ways).

### CODE REVIEW

**Comment by symtor** [comment]
It looks very inconvenient for writing header files, but I agree that it's best practice and justified.

**Comment by alalazo** [comment]
@epfl-ecps/dev At the moment I removed all `using namespace` directives from the header files. Question: are there any reasons to have so many namespaces (`cfbasics`, `channelflow`, `nsolver`, etc.)? Asking because if we are allowed to simplify that structure and have e.g. a single namespace we can mitigate (by far) the inconvenience noted by @symtor

**Comment by reetzelhaft** [comment]
I see @alalazo 's point in removing the `using namespace` directives from the header files and agree with it. However, I would not unify the different namespaces to make it more convenient for the developer who writes new code. More important to me is
1. Channelflow/NSolver is meant to be independent from each other so we should keep also the namespaces separate. 
2. Does it not help to better understand the code when reading it, if the type names show their origin by a specific namespace?

**Comment by alalazo** [comment]
@reetzelhaft A few free thoughts I have:
- Currently we are using 4 namespaces, i.e. `cfbasics`, `channelflow`, `channelflowtest`, `nsolver` that are **all declared at the same level, immediately on top of the global namespace**.
- Their names are kind of long, and this may clutter the code in header files.

The result is that, e.g. in namespace `channelflow`, we are forced to declare things like:
```c++
cfbasics::cfarray<cfbasics::Real> vec();
```
instead of the shorter:
```c++
cfarray<Real> vec();
```
because the classes we want don't live in the same namespace. I think we could organize things better, for ourselves and other people that will make use of the libraries we provide, if we:
- make use of nested namespaces
- put `cfbasics` in the base namespace
- shorten the base namespace name

This should also respect the request of having separate parts of the code declared in separate namespaces.

To be more explicit, I think we could:
1. Rename `cfbasics` to something shorter and more catchy. I'll propose `cfl` for the sake of this example (as it is just three letters and reminds of fluid-dynamics) but naming is absolutely tentative.
1. Rename `channelflow` into `cfl::flow` (again, naming is tentative the idea is that it should be in a **nested** namespace)
1. Rename `nsolver` into `cfl::nsolver`
1. Rename `channelflowtest` into `cfl::flow::test`

This should remove the need to use fully qualified namespace in most header files, will enforce the best practice of not having using directives in headers and will also restructure the namespaces in a way that fits better with the current architecture (after all, `channelflow` and `nsolver` depend both on `cfbasics`). Would that make sense to you?

**Comment by johnfgibson** [comment]
IMHO four namespaces for one project is overkill. I'm viewing your work at somewhat of a distance, of course, but I don't see a point for a distinction between `cfbasics` and `channelflow`, for instance. And I also feel that if you really want nsolver to be distinct from channelflow, supporting Newton solves of other dynamical systems, it should be in its own package in its own source tree. In that case its own namespace would be natural.

I strongly advise against the name `cfl`. You don't want people reading this and thinking "CFL number." In general acronyms are obvious to their authors and opaque to everyone else. The smallest reasonable namespace for channelflow is `chflow`, I think.

**Comment by alalazo** [comment]
@johnfgibson I sympathize with your opinion on having only one namespace. If that's not possible, for any reason, I think the next best thing is using nested namespaces.

> The smallest reasonable namespace for channelflow is chflow, I think.

:+1: A bit of context might be due. I am probably the only person in the team that has no scientific background in the field of fluid-dynamics - that's why I was stressing that the naming above was absolutely tentative. My point is more that we are in need of a shorter (and possibly unique) namespace. `chflow` fits perfectly imo.

@epfl-ecps/dev Do you all agree on having only a `chflow` namespace? If no further discussion is needed to reach an agreement I'll proceed cleaning the headers.

**Comment by reetzelhaft** [comment]
OK. I am fine with using a single namespace `chflow` for this project and understand that code modularity does not necessarily need to be reflected in the namespaces. However, once NSolver reaches the next levels of emancipation and becomes a truly independent project, one probably would change the namespace again.

**Comment by alalazo** [comment]
This is ready for review. Note that d092fb0 fixed a few issues with CI, you might want to have a look at that.

**Review by sajjadazimi — APPROVED** [review]

**Pull request merged**
